// Code generated by entc, DO NOT EDIT.

package guildchannel

const (
	// Label holds the string label denoting the guildchannel type in the database.
	Label = "guild_channel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChannel holds the string denoting the channel vertex property in the database.
	FieldChannel = "channel"

	// Table holds the table name of the guildchannel in the database.
	Table = "guild_channels"
	// GuildTable is the table the holds the guild relation/edge.
	GuildTable = "guild_channels"
	// GuildInverseTable is the table name for the Guild entity.
	// It exists in this package in order to avoid circular dependency with the "guild" package.
	GuildInverseTable = "guilds"
	// GuildColumn is the table column denoting the guild relation/edge.
	GuildColumn = "guild_id"
)

// Columns holds all SQL columns are guildchannel fields.
var Columns = []string{
	FieldID,
	FieldChannel,
}
