// Code generated by entc, DO NOT EDIT.

package guildchannel

import (
	"github.com/AlecAivazis/jeeves/db/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldID), id))
		},
	)
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldID), id))
		},
	)
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.NEQ(s.C(FieldID), id))
		},
	)
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			// if not arguments were provided, append the FALSE constants,
			// since we can't apply "IN ()". This will make this predicate falsy.
			if len(ids) == 0 {
				s.Where(sql.False())
				return
			}
			v := make([]interface{}, len(ids))
			for i := range v {
				v[i] = ids[i]
			}
			s.Where(sql.In(s.C(FieldID), v...))
		},
	)
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			// if not arguments were provided, append the FALSE constants,
			// since we can't apply "IN ()". This will make this predicate falsy.
			if len(ids) == 0 {
				s.Where(sql.False())
				return
			}
			v := make([]interface{}, len(ids))
			for i := range v {
				v[i] = ids[i]
			}
			s.Where(sql.NotIn(s.C(FieldID), v...))
		},
	)
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.GT(s.C(FieldID), id))
		},
	)
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.GTE(s.C(FieldID), id))
		},
	)
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.LT(s.C(FieldID), id))
		},
	)
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.LTE(s.C(FieldID), id))
		},
	)
}

// Channel applies equality check predicate on the "channel" field. It's identical to ChannelEQ.
func Channel(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldChannel), v))
		},
	)
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldRole), v))
		},
	)
}

// ChannelEQ applies the EQ predicate on the "channel" field.
func ChannelEQ(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldChannel), v))
		},
	)
}

// ChannelNEQ applies the NEQ predicate on the "channel" field.
func ChannelNEQ(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.NEQ(s.C(FieldChannel), v))
		},
	)
}

// ChannelIn applies the In predicate on the "channel" field.
func ChannelIn(vs ...string) predicate.GuildChannel {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			// if not arguments were provided, append the FALSE constants,
			// since we can't apply "IN ()". This will make this predicate falsy.
			if len(vs) == 0 {
				s.Where(sql.False())
				return
			}
			s.Where(sql.In(s.C(FieldChannel), v...))
		},
	)
}

// ChannelNotIn applies the NotIn predicate on the "channel" field.
func ChannelNotIn(vs ...string) predicate.GuildChannel {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			// if not arguments were provided, append the FALSE constants,
			// since we can't apply "IN ()". This will make this predicate falsy.
			if len(vs) == 0 {
				s.Where(sql.False())
				return
			}
			s.Where(sql.NotIn(s.C(FieldChannel), v...))
		},
	)
}

// ChannelGT applies the GT predicate on the "channel" field.
func ChannelGT(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.GT(s.C(FieldChannel), v))
		},
	)
}

// ChannelGTE applies the GTE predicate on the "channel" field.
func ChannelGTE(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.GTE(s.C(FieldChannel), v))
		},
	)
}

// ChannelLT applies the LT predicate on the "channel" field.
func ChannelLT(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.LT(s.C(FieldChannel), v))
		},
	)
}

// ChannelLTE applies the LTE predicate on the "channel" field.
func ChannelLTE(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.LTE(s.C(FieldChannel), v))
		},
	)
}

// ChannelContains applies the Contains predicate on the "channel" field.
func ChannelContains(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.Contains(s.C(FieldChannel), v))
		},
	)
}

// ChannelHasPrefix applies the HasPrefix predicate on the "channel" field.
func ChannelHasPrefix(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.HasPrefix(s.C(FieldChannel), v))
		},
	)
}

// ChannelHasSuffix applies the HasSuffix predicate on the "channel" field.
func ChannelHasSuffix(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.HasSuffix(s.C(FieldChannel), v))
		},
	)
}

// ChannelEqualFold applies the EqualFold predicate on the "channel" field.
func ChannelEqualFold(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.EqualFold(s.C(FieldChannel), v))
		},
	)
}

// ChannelContainsFold applies the ContainsFold predicate on the "channel" field.
func ChannelContainsFold(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.ContainsFold(s.C(FieldChannel), v))
		},
	)
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.EQ(s.C(FieldRole), v))
		},
	)
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.NEQ(s.C(FieldRole), v))
		},
	)
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.GuildChannel {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			// if not arguments were provided, append the FALSE constants,
			// since we can't apply "IN ()". This will make this predicate falsy.
			if len(vs) == 0 {
				s.Where(sql.False())
				return
			}
			s.Where(sql.In(s.C(FieldRole), v...))
		},
	)
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.GuildChannel {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			// if not arguments were provided, append the FALSE constants,
			// since we can't apply "IN ()". This will make this predicate falsy.
			if len(vs) == 0 {
				s.Where(sql.False())
				return
			}
			s.Where(sql.NotIn(s.C(FieldRole), v...))
		},
	)
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.GT(s.C(FieldRole), v))
		},
	)
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.GTE(s.C(FieldRole), v))
		},
	)
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.LT(s.C(FieldRole), v))
		},
	)
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.LTE(s.C(FieldRole), v))
		},
	)
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.Contains(s.C(FieldRole), v))
		},
	)
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.HasPrefix(s.C(FieldRole), v))
		},
	)
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.HasSuffix(s.C(FieldRole), v))
		},
	)
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.EqualFold(s.C(FieldRole), v))
		},
	)
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			s.Where(sql.ContainsFold(s.C(FieldRole), v))
		},
	)
}

// HasGuild applies the HasEdge predicate on the "guild" edge.
func HasGuild() predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			t1 := s.Table()
			s.Where(sql.NotNull(t1.C(GuildColumn)))
		},
	)
}

// HasGuildWith applies the HasEdge predicate on the "guild" edge with a given conditions (other predicates).
func HasGuildWith(preds ...predicate.Guild) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			builder := sql.Dialect(s.Dialect())
			t1 := s.Table()
			t2 := builder.Select(FieldID).From(builder.Table(GuildInverseTable))
			for _, p := range preds {
				p(t2)
			}
			s.Where(sql.In(t1.C(GuildColumn), t2))
		},
	)
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.GuildChannel) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			for _, p := range predicates {
				p(s)
			}
		},
	)
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.GuildChannel) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			for i, p := range predicates {
				if i > 0 {
					s.Or()
				}
				p(s)
			}
		},
	)
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GuildChannel) predicate.GuildChannel {
	return predicate.GuildChannel(
		func(s *sql.Selector) {
			p(s.Not())
		},
	)
}
