// Code generated by entc, DO NOT EDIT.

package guild

const (
	// Label holds the string label denoting the guild type in the database.
	Label = "guild"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDiscordID holds the string denoting the discordid vertex property in the database.
	FieldDiscordID = "discord_id"

	// Table holds the table name of the guild in the database.
	Table = "guilds"
	// BankTable is the table the holds the bank relation/edge.
	BankTable = "guild_banks"
	// BankInverseTable is the table name for the GuildBank entity.
	// It exists in this package in order to avoid circular dependency with the "guildbank" package.
	BankInverseTable = "guild_banks"
	// BankColumn is the table column denoting the bank relation/edge.
	BankColumn = "guild_id"
)

// Columns holds all SQL columns are guild fields.
var Columns = []string{
	FieldID,
	FieldDiscordID,
}
