// Code generated by entc, DO NOT EDIT.

package guild

const (
	// Label holds the string label denoting the guild type in the database.
	Label = "guild"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldID holds the string denoting the id vertex property in the database.
	FieldID = "id"

	// Table holds the table name of the guild in the database.
	Table = "guilds"
	// ChannelsTable is the table the holds the channels relation/edge.
	ChannelsTable = "guild_channels"
	// ChannelsInverseTable is the table name for the GuildChannel entity.
	// It exists in this package in order to avoid circular dependency with the "guildchannel" package.
	ChannelsInverseTable = "guild_channels"
	// ChannelsColumn is the table column denoting the channels relation/edge.
	ChannelsColumn = "guild_id"
	// BankTable is the table the holds the bank relation/edge.
	BankTable = "bank_items"
	// BankInverseTable is the table name for the BankItem entity.
	// It exists in this package in order to avoid circular dependency with the "bankitem" package.
	BankInverseTable = "bank_items"
	// BankColumn is the table column denoting the bank relation/edge.
	BankColumn = "guild_id"
)

// Columns holds all SQL columns are guild fields.
var Columns = []string{
	FieldID,
	FieldID,
}
