// Code generated by entc, DO NOT EDIT.

package bankitem

const (
	// Label holds the string label denoting the bankitem type in the database.
	Label = "bank_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the bankitem in the database.
	Table = "bank_items"
)

// Columns holds all SQL columns are bankitem fields.
var Columns = []string{
	FieldID,
}
