// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// BankItem is the predicate function for bankitem builders.
type BankItem func(*sql.Selector)
