// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// BankItem is the predicate function for bankitem builders.
type BankItem func(*sql.Selector)

// Guild is the predicate function for guild builders.
type Guild func(*sql.Selector)

// GuildChannel is the predicate function for guildchannel builders.
type GuildChannel func(*sql.Selector)
