// Code generated by entc, DO NOT EDIT.

package db

import (
	"context"
	"fmt"

	"github.com/AlecAivazis/jeeves/db/bankitem"
	"github.com/AlecAivazis/jeeves/db/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
)

// BankItemUpdate is the builder for updating BankItem entities.
type BankItemUpdate struct {
	config
	predicates []predicate.BankItem
}

// Where adds a new predicate for the builder.
func (biu *BankItemUpdate) Where(ps ...predicate.BankItem) *BankItemUpdate {
	biu.predicates = append(biu.predicates, ps...)
	return biu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (biu *BankItemUpdate) Save(ctx context.Context) (int, error) {
	return biu.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (biu *BankItemUpdate) SaveX(ctx context.Context) int {
	affected, err := biu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (biu *BankItemUpdate) Exec(ctx context.Context) error {
	_, err := biu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (biu *BankItemUpdate) ExecX(ctx context.Context) {
	if err := biu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (biu *BankItemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	var (
		builder  = sql.Dialect(biu.driver.Dialect())
		selector = builder.Select(bankitem.FieldID).From(builder.Table(bankitem.Table))
	)
	for _, p := range biu.predicates {
		p(selector)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err = biu.driver.Query(ctx, query, args, rows); err != nil {
		return 0, err
	}
	defer rows.Close()
	var ids []int
	for rows.Next() {
		var id int
		if err := rows.Scan(&id); err != nil {
			return 0, fmt.Errorf("db: failed reading id: %v", err)
		}
		ids = append(ids, id)
	}
	if len(ids) == 0 {
		return 0, nil
	}

	tx, err := biu.driver.Tx(ctx)
	if err != nil {
		return 0, err
	}
	if err = tx.Commit(); err != nil {
		return 0, err
	}
	return len(ids), nil
}

// BankItemUpdateOne is the builder for updating a single BankItem entity.
type BankItemUpdateOne struct {
	config
	id int
}

// Save executes the query and returns the updated entity.
func (biuo *BankItemUpdateOne) Save(ctx context.Context) (*BankItem, error) {
	return biuo.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (biuo *BankItemUpdateOne) SaveX(ctx context.Context) *BankItem {
	bi, err := biuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return bi
}

// Exec executes the query on the entity.
func (biuo *BankItemUpdateOne) Exec(ctx context.Context) error {
	_, err := biuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (biuo *BankItemUpdateOne) ExecX(ctx context.Context) {
	if err := biuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (biuo *BankItemUpdateOne) sqlSave(ctx context.Context) (bi *BankItem, err error) {
	var (
		builder  = sql.Dialect(biuo.driver.Dialect())
		selector = builder.Select(bankitem.Columns...).From(builder.Table(bankitem.Table))
	)
	bankitem.ID(biuo.id)(selector)
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err = biuo.driver.Query(ctx, query, args, rows); err != nil {
		return nil, err
	}
	defer rows.Close()
	var ids []int
	for rows.Next() {
		var id int
		bi = &BankItem{config: biuo.config}
		if err := bi.FromRows(rows); err != nil {
			return nil, fmt.Errorf("db: failed scanning row into BankItem: %v", err)
		}
		id = bi.ID
		ids = append(ids, id)
	}
	switch n := len(ids); {
	case n == 0:
		return nil, &ErrNotFound{fmt.Sprintf("BankItem with id: %v", biuo.id)}
	case n > 1:
		return nil, fmt.Errorf("db: more than one BankItem with the same id: %v", biuo.id)
	}

	tx, err := biuo.driver.Tx(ctx)
	if err != nil {
		return nil, err
	}
	if err = tx.Commit(); err != nil {
		return nil, err
	}
	return bi, nil
}
