// Code generated by entc, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"log"

	"github.com/AlecAivazis/jeeves/db/migrate"

	"github.com/AlecAivazis/jeeves/db/bankitem"

	"github.com/facebookincubator/ent/dialect"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// BankItem is the client for interacting with the BankItem builders.
	BankItem *BankItemClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	c := config{log: log.Println}
	c.options(opts...)
	return &Client{
		config:   c,
		Schema:   migrate.NewSchema(c.driver),
		BankItem: NewBankItemClient(c),
	}
}

// Open opens a connection to the database specified by the driver name and a
// driver-specific data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil

	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("db: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("db: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug}
	return &Tx{
		config:   cfg,
		BankItem: NewBankItemClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		BankItem.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true}
	return &Client{
		config:   cfg,
		Schema:   migrate.NewSchema(cfg.driver),
		BankItem: NewBankItemClient(cfg),
	}
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// BankItemClient is a client for the BankItem schema.
type BankItemClient struct {
	config
}

// NewBankItemClient returns a client for the BankItem from the given config.
func NewBankItemClient(c config) *BankItemClient {
	return &BankItemClient{config: c}
}

// Create returns a create builder for BankItem.
func (c *BankItemClient) Create() *BankItemCreate {
	return &BankItemCreate{config: c.config}
}

// Update returns an update builder for BankItem.
func (c *BankItemClient) Update() *BankItemUpdate {
	return &BankItemUpdate{config: c.config}
}

// UpdateOne returns an update builder for the given entity.
func (c *BankItemClient) UpdateOne(bi *BankItem) *BankItemUpdateOne {
	return c.UpdateOneID(bi.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *BankItemClient) UpdateOneID(id int) *BankItemUpdateOne {
	return &BankItemUpdateOne{config: c.config, id: id}
}

// Delete returns a delete builder for BankItem.
func (c *BankItemClient) Delete() *BankItemDelete {
	return &BankItemDelete{config: c.config}
}

// DeleteOne returns a delete builder for the given entity.
func (c *BankItemClient) DeleteOne(bi *BankItem) *BankItemDeleteOne {
	return c.DeleteOneID(bi.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *BankItemClient) DeleteOneID(id int) *BankItemDeleteOne {
	return &BankItemDeleteOne{c.Delete().Where(bankitem.ID(id))}
}

// Create returns a query builder for BankItem.
func (c *BankItemClient) Query() *BankItemQuery {
	return &BankItemQuery{config: c.config}
}

// Get returns a BankItem entity by its id.
func (c *BankItemClient) Get(ctx context.Context, id int) (*BankItem, error) {
	return c.Query().Where(bankitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BankItemClient) GetX(ctx context.Context, id int) *BankItem {
	bi, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return bi
}
