// Code generated by entc, DO NOT EDIT.

package db

import (
	"context"
	"log"

	"github.com/facebookincubator/ent/dialect/sql"
)

// dsn for the database. In order to run the tests locally, run the following command:
//
//	 DB_INTEGRATION_ENDPOINT="root:pass@tcp(localhost:3306)/test?parseTime=True" go test -v
//
var dsn string

func ExampleBankItem() {
	if dsn == "" {
		return
	}
	ctx := context.Background()
	drv, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed creating database client: %v", err)
	}
	defer drv.Close()
	client := NewClient(Driver(drv))
	// creating vertices for the bankitem's edges.

	// create bankitem vertex with its edges.
	bi := client.BankItem.
		Create().
		SetItemID("string").
		SetQuantity(1).
		SaveX(ctx)
	log.Println("bankitem created:", bi)

	// query edges.

	// Output:
}
