// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// BankItemsColumns holds the columns for the "bank_items" table.
	BankItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// BankItemsTable holds the schema information for the "bank_items" table.
	BankItemsTable = &schema.Table{
		Name:        "bank_items",
		Columns:     BankItemsColumns,
		PrimaryKey:  []*schema.Column{BankItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BankItemsTable,
	}
)

func init() {
}
