// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// BankItemsColumns holds the columns for the "bank_items" table.
	BankItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "item_id", Type: field.TypeString},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "bank_id", Type: field.TypeInt, Nullable: true},
	}
	// BankItemsTable holds the schema information for the "bank_items" table.
	BankItemsTable = &schema.Table{
		Name:       "bank_items",
		Columns:    BankItemsColumns,
		PrimaryKey: []*schema.Column{BankItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "bank_items_guild_banks_items",
				Columns: []*schema.Column{BankItemsColumns[3]},

				RefColumns: []*schema.Column{GuildBanksColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// GuildsColumns holds the columns for the "guilds" table.
	GuildsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "discord_id", Type: field.TypeString, Unique: true},
	}
	// GuildsTable holds the schema information for the "guilds" table.
	GuildsTable = &schema.Table{
		Name:        "guilds",
		Columns:     GuildsColumns,
		PrimaryKey:  []*schema.Column{GuildsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// GuildBanksColumns holds the columns for the "guild_banks" table.
	GuildBanksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "channel_id", Type: field.TypeString},
		{Name: "display_message_id", Type: field.TypeString, Unique: true},
		{Name: "balance", Type: field.TypeInt},
		{Name: "guild_id", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// GuildBanksTable holds the schema information for the "guild_banks" table.
	GuildBanksTable = &schema.Table{
		Name:       "guild_banks",
		Columns:    GuildBanksColumns,
		PrimaryKey: []*schema.Column{GuildBanksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "guild_banks_guilds_bank",
				Columns: []*schema.Column{GuildBanksColumns[4]},

				RefColumns: []*schema.Column{GuildsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BankItemsTable,
		GuildsTable,
		GuildBanksTable,
	}
)

func init() {
	BankItemsTable.ForeignKeys[0].RefTable = GuildBanksTable
	GuildBanksTable.ForeignKeys[0].RefTable = GuildsTable
}
